[helpers]

[vim.files]
"vim" = { target = "~/.vim", type = "symbolic", recurse = false }

[lazyvim.files]
"lazyvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[spacemacs.files]
"spacemacs" = "~/.spacemacs"

[tmux.files]
"tmux.conf" = "~/.tmux.conf"

[zellij.files]
"zellij.kdl" = "~/.config/zellij/config.kdl"

[doom.files]
"doom/" = "~/.config/doom"

[git.files]
"gitconfig" = "~/.gitconfig"

[lazygit.files]
"lazygit.yml" = "~/.config/lazygit/config.yml"

[fish.files]
"fish" = { target = "~/.config/fish", type = "symbolic", recurse = false }

[zsh.files]
"zsh/zshrc.local" = "~/.zshrc.local"
"zsh/zshrc" = "~/.zshrc"

[bash.files]
"bash/inputrc" = "~/.inputrc"

[wezterm.files]
"wezterm.lua" = "~/.config/wezterm/wezterm.lua"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[helix.files]
"helix.toml" = "~/.config/helix/config.toml"

[ghostty.files]
"ghostty.conf" = "~/.config/ghostty/config"
