[helpers]

[vim.files]
"vim" = { target = "~/.vim", type = "symbolic", recurse = false }

[spacemacs.files]
"spacemacs" = "~/.spacemacs"

[tmux.files]
"tmux.conf" = "~/.tmux.conf"

[zellij.files]
"zellij.kdl" = "~/.config/zellij/config.kdl"

[doom.files]
"doom/" = "~/.config/doom"
