[helpers]

[vim.files]
"vim" = { target = "~/.vim", type = "symbolic", recurse = false }

[spacemacs.files]
"spacemacs" = "~/.spacemacs"

[tmux.files]
"tmux.conf" = "~/.tmux.conf"

[zellij.files]
"zellij.kdl" = "~/.config/zellij/config.kdl"

[doom.files]
"doom/" = "~/.config/doom"

[git.files]
"gitconfig" = "~/.gitconfig"

[zsh.files]
"zsh/zshrc.local" = "~/.zshrc.local"
"zsh/zshrc" = "~/.zshrc"

[wezterm.files]
"wezterm.lua" = "~/.config/wezterm/wezterm.lua"
